robot2:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  joint0_position_controller:
    type: effort_controllers/JointPositionController
    joint: J_0
    pid: {p: 2000.0, i: 100, d: 500.0}
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: J_1
    pid: {p: 50000.0, i: 100, d: 2000.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: J_2
    pid: {p: 20000.0, i: 50, d: 1000.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: J_3
    pid: {p: 2000.0, i: 50, d: 200.0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: J_4
    pid: {p: 700.0, i: 50, d: 70.0}

